/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ConMenuKelas;
import controller.ConMenuUtama;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import model.ModelMenuUtama;


/**
 *
 * @author USER 10
 */
public class MenuUtama extends javax.swing.JFrame {
    /**
     * Creates new form MenuUtama
     */
    String temp; //menyimpan kelas
    
    public MenuUtama() {
        initComponents();
        this.setVisible(true);
        ConMenuUtama controller = new ConMenuUtama();
        controller.setTabel(tabel);
        
        buatkelas.setEnabled(false);
        hapus.setEnabled(false);
        bukakelas.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tekskelas = new javax.swing.JTextField();
        buatkelas = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        kelasedit = new javax.swing.JLabel();
        bukakelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jLabel1.setText("Menu Utama");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "Kelas"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        tekskelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekskelasActionPerformed(evt);
            }
        });
        tekskelas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tekskelasPropertyChange(evt);
            }
        });

        buatkelas.setText("Buat Kelas");
        buatkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatkelasActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jLabel2.setText("Kelas :");

        bukakelas.setText("Buka Kelas");
        bukakelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bukakelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tekskelas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(8, 8, 8)
                                        .addComponent(kelasedit)))
                                .addGap(18, 18, 18)
                                .addComponent(buatkelas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bukakelas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tekskelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buatkelas))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kelasedit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapus)
                            .addComponent(bukakelas))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        
        //mengambil data id barang yang diklik mouse
        try{
            //ketika tabel diklik maka kelas akan muncul
            temp = (String) model.getValueAt(tabel.getSelectedRow(), 1);
            kelasedit.setText(temp);
            bukakelas.setEnabled(true);
            hapus.setEnabled(true);
        }
        catch(NumberFormatException e) //jika data kosong atau terjadi error selain itu
        {
            System.out.println("Menu Utama. error =  "+e);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        //ketika tombol hapus diklik
        ConMenuUtama controller = new ConMenuUtama();
        controller.deleteTabel(temp, tabel);
    }//GEN-LAST:event_hapusActionPerformed

    private void buatkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatkelasActionPerformed
        // TODO add your handling code here:
        ConMenuUtama controller = new ConMenuUtama();
        if(tekskelas.getText().contains(" "))
            {
                tekskelas.setText("jangan ada spasi");
            }
            else{
                try{
                controller.createTabel(tekskelas.getText(), tabel);
                }
            catch(Exception e)
                {
                    tekskelas.setText("isi teks field ini");
                }
            }
        
        
    }//GEN-LAST:event_buatkelasActionPerformed

    private void tekskelasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tekskelasPropertyChange
        // TODO add your handling code here:
        if(tekskelas.getText() == null)
        {
            buatkelas.setEnabled(false);
        }
        else if(tekskelas.getText() != null)
        {
            buatkelas.setEnabled(true);
        }
    }//GEN-LAST:event_tekskelasPropertyChange

    private void tekskelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekskelasActionPerformed
        // TODO add your handling code here:
        buatkelas.setEnabled(true);
        
    }//GEN-LAST:event_tekskelasActionPerformed

    private void bukakelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bukakelasActionPerformed
        // TODO add your handling code here:
        ConMenuKelas controller = new ConMenuKelas(kelasedit.getText());
        this.dispose();
    }//GEN-LAST:event_bukakelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatkelas;
    private javax.swing.JButton bukakelas;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kelasedit;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tekskelas;
    // End of variables declaration//GEN-END:variables
}
